# Generated by Django 3.0.1 on 2020-01-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pas',
        ),
    ]
